"""Inicializar tablas

Revision ID: 61a1d4c3e0b4
Revises: 
Create Date: 2025-06-13 15:59:50.641351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61a1d4c3e0b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('expenses', sa.Column('create', sa.DateTime(), nullable=False))
    op.add_column('expenses', sa.Column('update', sa.DateTime(), nullable=False))
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'update_at')
    op.drop_column('expenses', 'desciption')
    op.add_column('incomes', sa.Column('create', sa.DateTime(), nullable=False))
    op.add_column('incomes', sa.Column('update', sa.DateTime(), nullable=False))
    op.drop_column('incomes', 'created_at')
    op.drop_column('incomes', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('incomes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('incomes', 'update')
    op.drop_column('incomes', 'create')
    op.add_column('expenses', sa.Column('desciption', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'update')
    op.drop_column('expenses', 'create')
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###
